### ISSUE TITLE
PC: Añadir acceso a la tienda

### ISSUE THREAD

**Issue by mrf1989** [youRoom-ISPP/youRoom#101]
Se debe crear una opción de menú que lleve directamente a la tienda donde se podrán comprar todos los productos.

Además, se requiere de un botón que envíe directamente a la suscripción en la vista de perfil. Si el usuario ya es premium, este botón será de cancelar la recurrencia de la suscripción.

**Comment by jorandmol** [comment]
He creado el acceso a la tienda en el menú, tanto para móvil como para pantallas grandes y he añadido el enlace directo a la compra de la suscripción (o botón de cancelación) en la vista de perfil:
![image](https://user-images.githubusercontent.com/56023983/114701173-bcfbce80-9d22-11eb-975a-22583f055d82.png)
![image](https://user-images.githubusercontent.com/56023983/114701103-a786a480-9d22-11eb-8ec8-cfba72177edf.png)

Aunque de lo último no estoy muy satisfecho. Creo que quedaría mejor si se sustituye el botón de "cerrar sesión" por un simple icono de apagado/encendido.

Me gustaría saber qué os parece, @juacormun y @alemunara, ya que todavía no voy a abrir una petición de pull porque falta meter los enlaces directos a la compra y cancelación de la suscripción.
