### ISSUE TITLE
PC: Añadir pruebas para la pasarela

### ISSUE THREAD

**Issue by jorandmol** [youRoom-ISPP/youRoom#122]
Se necesitan pruebas en el controlador de la pasarela de cobro ya que, debido a la necesidad de tener implementada la funcionalidad con rapidez, se han pasado por alto.

**Comment by javsolgar** [comment]
Se ha intentado implementar las pruebas desde el view, pero creemos que su implementación es muy compleja y no conseguimos avanzar.

Proponemos pruebas de interfaz, las cuales se alternarían con consultas a Stripe para comprobar el correcto funcionamiento de la API.

En cuanto las pruebas de existentes en esta rama, la de comprobar se ha quedado desfasada tras la nueva implementación sobre la fecha de cancelación, por lo que se puede eliminar sin ningún problema.
