### ISSUE TITLE
AU: Vista de login

### ISSUE THREAD

**Issue by fragonlug** [youRoom-ISPP/youRoom#15]
Crear la vista de la página de inicio con, únicamente, el formulario de usuario y contraseña

**Comment by jorandmol** [comment]
He completado, provisionalmente, la vista de login de los usuarios. Para ello he modificado el archivo login.html existente y he creado una hoja de estilos llamada base.css.

Para dar esta tarea por finalizada completamente se debe esperar a que la interfaz base esté disponible en la rama develop e integrarla. Además, me gustaría aumentar el tamaño del icono y centrar la tarjeta con el formulario, la cual tiene algo de espacio sobrante debajo. También es necesario ajustar la vista para pantallas más grandes.

Aquí dejo una imagen del estado actual:
![login](https://user-images.githubusercontent.com/56023983/111834915-8df56700-88f4-11eb-804c-4c6208fb816e.jpg)

**Comment by jorandmol** [comment]
Con la interfaz base completada y disponible en la rama develop me he encargado de integrar los estilos, además de realizar ciertas correcciones que explico en este [commit](https://github.com/youRoom-ISPP/youRoom/commit/acebf364ff32ff3c00b477f092d6730c5825e181).

Estoy a la espera de que @fragonlug y @alfgonfer terminen la tarea #6 para hacer la integración de las capas de frontend y backend.
