### ISSUE TITLE
Resolución de errores de interfaz

### ISSUE THREAD

**Issue by ferruirob** [youRoom-ISPP/youRoom#153]
Se deben solucionar una serie de pequeños errores de la interfaz de la aplicación, en concreto:
- [x] En el formulario de registro, cambiar el placeholder de username por "Nombre de usuario".
- [x] Hacer que el logo de la página (en el encabezado) redirija a /timeline.
- [x] Centrar correctamente los botones de menú y disminuir su altura, ambos en versión móvil.
- [x] Poner el icono de estrella con el que está puesto en el perfil.
- [x] En tamaños de tablets, ampliar el logo.
- [x] Cambiar el orden de los comentarios para que parezca una conversación.
- [x] Poner la foto de perfil en todas las vistas y añadir la clase "px-minimo" en los card-headers.
- [x] Solucionar error en la vista de perfil en el móvil.

**Comment by mrf1989** [comment]
Opino que se debería optar por "Nombre de usuario" para el input correspondiente del formulario de registro.
