### ISSUE TITLE
LR: Vista del ranking

### ISSUE THREAD

**Issue by fragonlug** [youRoom-ISPP/youRoom#17]
Realizar la interfaz del listado del ranking de usuarios

**Comment by jorandmol** [comment]
Ya he obtenido la base de la vista de ranking, tal y como aparece en los mockups. Previo a la realización de la PR me encargaré de darle estilo y apariencia agradable.

Para poder hacerlo tuve que implementar la lógica básica para que se listen los usuarios de la aplicación. Los encargados de la capa de backend del ranking, en concreto de la tarea #37, deberán de mejorar la consulta calculando los puntos y ordenando el listado por ellos.
