### ISSUE TITLE
Diseño de iconos e imágenes de la web

### ISSUE THREAD

**Issue by fragonlug** [youRoom-ISPP/youRoom#18]
Creación de los iconos e imágenes propias de la web como puede ser el logo, icono de "me gusta", etc.

**Comment by mrf1989** [comment]
@juacormun ¿Cómo te viene que revisemos el tema del logotipo y algunos estáticos mañana martes 23? Estaría bien ir cerrando tareas como esta. Queda pendiente hacer una composición de un móvil con una demo del timeline, para poner como estático de adorno en la vista de login.

**Comment by jcbuildr** [comment]
Bien, quedamos mañana si quieres. Por cierto, si me avisas por Telegram mejor, que aquí no me saltan notificaciones, lo he visto por casualidad desde el correo.

**Comment by mrf1989** [comment]
Voy a pasar esta tarea de nuevo a "en progreso". No sé si @jorandmol la pasó por error a "hecho". Pero faltan algunos estáticos como comenté, de cara al final de sprint.

**Comment by mrf1989** [comment]
@juacormun He detectado que el logo de la caja de login no tiene la "R" un poco más oscura como hablamos. A ver si le puedes pegar un vistazo a esto.

**Comment by mrf1989** [comment]
Ya tengo hecho por aquí el diseño para el login en vistas desktop.

Me falta que @juacormun cambie el logo que aparece en la caja de login, por el logo con la "R" más oscura.

![smartphones](https://user-images.githubusercontent.com/18377908/112729730-ef898700-8f2d-11eb-8833-f675a238a854.png)

**Comment by mrf1989** [comment]
Esta tarea se va a dar por cerrada, ya que tenemos todos los estáticos gráficos para el sitio terminados. Si nos surge la necesidad de alguno nuevo se abrirá una nueva tarea, pero por lo general ya están terminados los necesarios.
