### ISSUE TITLE
Análisis de requisitos

### ISSUE THREAD

**Issue by fragonlug** [youRoom-ISPP/youRoom#3]

**Comment by mrf1989** [comment]
@fragonlug ¿Qué pasa con esta tarea?

**Comment by mrf1989** [comment]
@fragonlug ¿Dónde se localiza toda esta información? ¿Y los UML definitivos hasta la fecha?

**Comment by mrf1989** [comment]
@fragonlug ¿Se sabe dónde está definitivamente este material? Tendría que incluirse, junto con los modelos UML (issue #5), en la wiki y damos por cerrada la tarea.
