### ISSUE TITLE
AU: Solucionar el error de login del CSRF Token

### ISSUE THREAD

**Issue by jorandmol** [youRoom-ISPP/youRoom#32]
Al tratar de iniciar sesión a través del formulario de login, aparece un error, concreatamente este:

``Forbidden (CSRF token missing or incorrect.)``

Para que se de, lo único que sucedió y que entiendo que pueda ser su causa es que mantuve la aplicación desplegada mucho tiempo, por lo que puede que el token expirase.

Para solucionar esta incidencia he encontrado información en una [web](https://stackoverflow.com/questions/12731305/django-csrf-token-missing-or-incorrect) que parece tener la respuesta.

**Comment by alfgonfer** [comment]
Se ha estudiado el problema planteado.
No hemos conseguido replicar el fallo. Puede haberse arreglado tras la resolución de la incidencia #33. Hemos estado con la aplicación abierta tras iniciar sesión un largo rato. Ahora, al acceder de nuevo a "/", si ya has iniciado sesión se te redirecciona a timeline, por lo que no es posible volver a iniciar sesión.
