### ISSUE TITLE
AU: Redirección a timeline si se está logueado

### ISSUE THREAD

**Issue by jorandmol** [youRoom-ISPP/youRoom#33]
Se debe corregir el flujo de la aplicación de forma que si un usuario ya se ha logueado sea redirigido directamente a la pestaña principal (timeline).

Este error surge al haber iniciado sesión previamente y, tras cerrar el navegador o reiniciar el servidor, se accede de nuevo a localhost:8000. De forma errónea se mostrará la vista de login con el header y footer propio del resto de interfaces de la aplicación.

Como sugerencia para su resolución, planteo cambiar los endpoints de la aplicación: el listado de publicaciones sería la vista principal (en el endpoint "/") y que se requiera estar logueado para entrar, redirigiendo a "/login".

**Puede que el causante del error de la incidencia #32 provenga del hecho de tratar de loguearse cuando ya se ha iniciado sesión previamente.**

**Comment by alfgonfer** [comment]
Se ha estudiado el problema planteado.
Tras esto, hemos investigado y la solución ha sido añadir al método de usuario/views.py una línea que redirija a timeline en caso de que el usuario este _loggeado_, por lo que no ha hecho falta cambiar la dirección a /login.
