### ISSUE TITLE
LP: Tratar la pérdida de imágenes

### ISSUE THREAD

**Issue by jorandmol** [youRoom-ISPP/youRoom#36]
Durante todas las etapas de desarrollo de la aplicación, incluso cuando se haya puesto en producción, puede ocurrir que las imágenes que se hayan subido se pierdan o se corrompan. Si esto ocurre, en la vista del listado de publicaciones aparece el símbolo de imagen rota. 

El error se identifica borrando cualquiera de los archivos de imagen que se encuentran en la carpeta media del proyecto. Si tras ello se navega hasta el timeline se puede ver el símbolo en cuestión, hecho que arruina la experiencia del usuario.

Propongo solucionarlo mediante una o varias imágenes por defecto que se mantenga en el directorio de las imágenes. Desde el controlador de publicación se comprueba que la imagen establecida por el usuario exista y, si esto no ocurre, se muestra una habitación genérica (por ejemplo).

**Comment by mrf1989** [comment]
@marmolpen3 ¿Esta issue la podemos dar por cerrada o queda algo pendiente?
