### ISSUE TITLE
PU: Obtención de usuario

### ISSUE THREAD

**Issue by alemunara** [youRoom-ISPP/youRoom#55]
Se ha detectado un error a la hora en obtener el usuario en perfil de usuario. 

Al intentar integrar el frontend y el backend, se ha encontrado que el usuario no se pasa de forma correcta y por tanto queda inutilizable en la parte frontend.

El error se ha detectado en el archivo views.py de perfil de usuario.

**Comment by fragonlug** [comment]
Se ha comprobado que el usuario se pasa de forma correcta, se debe tener en cuenta que si se desea acceder al User de Django, se debe hacer a través de la propiedad user de UsuarioPerfil.
