### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by fragonlug** [youRoom-ISPP/youRoom#62]

**Comment by mrf1989** [comment]
Para la promoción de la aplicación de cara al lanzamiento de la primera versión en producción, se van a realizar las siguientes creatividades:
- Banners publicitarios para insertar en redes sociales (Youtube, Facebook e Instagram).
- Elevator pitch
- Spot de 30 segundos (versión corta de 15 segundos para redes).

**Comment by mrf1989** [comment]
### Banner para Facebook
![banner-facebook](https://user-images.githubusercontent.com/18377908/113142265-fadcfb00-922a-11eb-814a-b29688cd670b.jpg)

### Banner para Youtube
![banner-youtube](https://user-images.githubusercontent.com/18377908/113142283-00d2dc00-922b-11eb-8fe2-1d26bf1f7094.jpg)

### Banner para story de Instagram
![banner-story-ig](https://user-images.githubusercontent.com/18377908/113142297-04666300-922b-11eb-938e-3181b87f0836.jpg)

**Comment by mrf1989** [comment]
### Elevator pitch

¿Tienes un pequeño negocio de decoración y quieres crecer dando el salto al comercio electrónico?

Presentamos youRoom, una red social para los amantes del interiorismo y la decoración.

Internet ha obligado a las empresas pequeñas a promocionar sus productos en la red para poder competir con grandes marcas.

En youRoom, ofrecemos un escaparate perfecto para compartir contenido mediante fotografías, donde se pueden referenciar los puntos de venta online de los productos que en ellas aparecen. El resto de usuarios podrán puntuarlas y esto permite escalar posiciones en un ranking de usuarios.

A través de la creación de contenido de calidad, youRoom otorga visibilidad y notoriedad entre la comunidad, ayudando a incrementar las ventas y los beneficios de los pequeños negocios.

youRoom es un espacio moderno de encuentro entre clientes y empresas del sector de la decoración. Un lugar único donde inspirarse e inspirar a otros.

Descubre, reinventa y transforma registrándote en youRoom.

**Comment by mrf1989** [comment]
[Storyboard spot youRoom.docx](https://github.com/youRoom-ISPP/youRoom/files/6254267/Storyboard.spot.youRoom.docx)

**Comment by mrf1989** [comment]
Se ha reabierto el issue porque se ha continuado trabajando en el segundo sprint en un nuevo storyboard para otro spot.

Este segundo spot se enfoca a comerciales pequeños que puedan estar interesados en potenciar su imagen digital y mejorar las ventas en su página web.

[Storyboard spot 2 youRoom.docx](https://github.com/youRoom-ISPP/youRoom/files/6297454/Storyboard.spot.2.youRoom.docx)
