### ISSUE TITLE
RP: Limitar cantidad de enlaces

### ISSUE THREAD

**Issue by fragonlug** [youRoom-ISPP/youRoom#70]
Un usuario gratuito no podrá añadir más de dos enlaces a su publicación.

**Comment by mrf1989** [comment]
@fragonlug Esta es la tarea que te comenté que no tenía mucho sentido que estuviera asignada a backend, ya que se puede gestionar y tratar directamente del lado del cliente si se dispone de la tipología de usuario (free o premium).

Puedes realizar una reasignación de etiquetado del issue si lo consideras y lo aprovechamos para darle salida desde el frontend.
