### ISSUE TITLE
LR: No se muestra correctamente el ranking

### ISSUE THREAD

**Issue by fragonlug** [youRoom-ISPP/youRoom#75]
Al acceder a la vista del ranking, no se muestran los puntos y los nombres de usuario correspondientes a los usuarios.

Para replicarlo:
-Tener un usuario en el sistema
-Desplegar la aplicación
-Acceder a la vista de Ranking

El fallo se encuentra en el html de ranking, teniendo este que integrarse con el backend actual.

**Comment by mrf1989** [comment]
@fragonlug @jorandmol ¿Esta incidencia sigue sin resolverse o ya se hizo merge?
