### ISSUE TITLE
AU: Registro de usuario

### ISSUE THREAD

**Issue by fragonlug** [youRoom-ISPP/youRoom#99]
Realización del backend correspondiente para el correcto registro de un usuario en la plataforma.

- [x] Formulario con los campos correspondientes de un usuario de la plataforma.
- [x] Procesado de la creación del usuario en su clase correspondiente.
- [x] Añadir la correspondiente endpoint para el acceso al registro.

**Comment by mrf1989** [comment]
@fragonlug Una pequeña matización sobre el tercer checkbox. El endpoint que debéis crear es relativo al procesado del formulario, ya que no existirá una ruta tal como /registro o /registrar.

El usuario accederá a la principal. Ahí verá el formulario de login y un botón para registro. Si hace clic sobre él, le togueará el formulario. El action de dicho formulario nuevo apuntará al endpoint que sí tendríais que dar de alta en urls. El endpoint encargado de procesar la información de dicho formulario de registro.
